services:
  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  librarydb:
    container_name: librarydb
    environment:
      - ACCEPT_EULA=Y
      - BRENOADMIN_PASSWORD=bre@dmin12345
    restart: always
    ports:
      - "1433:1433"
